### PR TITLE
Adds 3.11.4 rns

### PR DESCRIPTION
**Pull request by stevsmit**

### CODE REVIEW

**Comment by stevsmit** [comment]
https://issues.redhat.com/browse/PROJQUAY-7594

**Comment by LiZhang19817** [comment]
Now https://issues.redhat.com/browse/PROJQUAY-7425 was fixed in **Quay 3.12.1,** is it necessary to guide Quay Customers to use S3Storage Engine with NetApp ONTAP S3？

**Comment by HammerMeetNail** [comment]
@LiZhang19817 @ibazulic Is https://issues.redhat.com/browse/PROJQUAY-7462 still an issue? Did we chalk that one up to network issues?

**Comment by ibazulic** [comment]
@HammerMeetNail no, that one is still an issue. It's not network related.

**Comment by HammerMeetNail** [comment]
Ok, we should probably hold off on stamping full support until it's fixed. Let me know if y'all think different.

**Comment by stevsmit** [comment]
@HammerMeetNail @LiZhang19817 Hiding the new config.yaml portion of this PR and saving it for a future PR. Thanks.

**Pull request closed without merging**
