### PR TITLE
Adds mirror config fields to config docs

### PR DESCRIPTION
**Pull request by stevsmit**
Issues:

https://issues.redhat.com/browse/PROJQUAY-3758
https://issues.redhat.com/browse/PROJQUAY-4742

Preview: https://stevsmit.github.io/quay-docs/api-example/index.html#external-registry-config-api-example

### CODE REVIEW

**Comment by huweihua-redhat** [comment]
@stevsmit 
I am not sure if my understanding is 100% correct. But I think what the [PROJQUAY-3758](https://issues.redhat.com/browse/PROJQUAY-3758) want to add is `external_registry_config`  object.  

Should we add description about `external_registry_config`  object in below three API sections?
* [CreateRepoMirrorConfig](https://access.redhat.com/documentation/en-us/red_hat_quay/3.6/html-single/red_hat_quay_api_guide/index#createrepomirrorconfig)
* [ChangeRepoMirrorConfig](https://access.redhat.com/documentation/en-us/red_hat_quay/3.6/html-single/red_hat_quay_api_guide/index#changerepomirrorconfig)
* [ViewMirrorConfig](https://access.redhat.com/documentation/en-us/red_hat_quay/3.6/html-single/red_hat_quay_api_guide/index#viewmirrorconfig)

I got the details of `external_registry_config`  object in  [PROJQUAY-3757](https://issues.redhat.com/browse/PROJQUAY-3757).

```
"external_registry_config": {
  "verify_tls": {{ quay_mirror_role_ext_registry_verify_tls }},
  "unsigned_images": {{ quay_mirror_role_ext_registry_unsigned_images }},
  "proxy": {
    "https_proxy": "{{ quay_mirror_role_https_proxy | default(omit) }}",
    "http_proxy": "{{ quay_mirror_role_http_proxy | default(omit) }}",
    "no_proxy": "{{ quay_mirror_role_no_proxy | default(omit) }}"
  }
}
```
If I didn't make mistake, I think these message should be included in the document.

**Comment by pbertera** [comment]
Yes, `external_registry_config` structure and fields should be documented in the API docs.

**Comment by stevsmit** [comment]
@huweihua-redhat @pbertera the API docs are auto-generated; adding the `external_registry_config` object reference would get removed each time the API docs are generated. I can create a new module for the API docs, but there's one other issue: 

we don't document any object details in the API guide, for example, `root rule`. This might set a weird precedent. Anyways, please check the preview for how I approached this. Thanks.

**Comment by stevsmit** [comment]
@pbertera @huweihua-redhat That sounds good to me, but I don't have a working example of `external_registry_config`. I couldn't find an example in the repo. 

Might either of you have one?

**Comment by pbertera** [comment]
@stevsmit you can find an example here: https://github.com/quay/quay/blob/master/endpoints/api/test/test_mirror.py#L28-L33

**Comment by huweihua-redhat** [comment]
LGTM 
Thanks a lot @stevsmit @pbertera .

**Pull request merged**
