### PR TITLE
Updates container limits fields for builders

### PR DESCRIPTION
**Pull request by stevsmit**
https://issues.redhat.com/browse/PROJQUAY-7723

### CODE REVIEW

**Comment by huweihua-redhat** [comment]
LGTM,  thanks @stevsmit

**Comment by stevsmit** [comment]
/cherry-pick f4a6150cb3420f4fd6e62af1402c07088cd2fe68 redhat-3.12

**Comment by stevsmit** [comment]
/cherry-pick https://github.com/quay/quay-docs/commit/f4a6150cb3420f4fd6e62af1402c07088cd2fe68 redhat-3.12

**Comment by stevsmit** [comment]
/cherry-pick https://github.com/quay/quay-docs/commit/f4a6150cb3420f4fd6e62af1402c07088cd2fe68 redhat-3.12

**Comment by stevsmit** [comment]
/cherry-pick https://github.com/quay/quay-docs/commit/f4a6150cb3420f4fd6e62af1402c07088cd2fe68 redhat-3.12

**Pull request merged**
